import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createMachine,frames} from '../scripts/headless.mjs';import {createCompanions,spawnItem,spawnBomb,tileKind,pickups,companionBombSlots,validateCompanionState,canOccupy,DEATH_FRAMES} from '../dist/campaign.js';import {launchSequence,createBattleAI} from '../dist/battle-ai.js';import {captureState,restoreState} from '../dist/save-state.js';
const rom=process.env.BOMBERMAN_TEST_ROM;
test('AI prioritizes and consumes upgrades, protects visible items, uses private powers and replays upgraded bombs',{skip:!rom},()=>{
 const p=createMachine(fs.readFileSync(rom)),crew=createCompanions(p);for(const a of launchSequence('solo'))frames(p,a.frames,a.button?[[0,a.button]]:[]);frames(p,2520);for(let i=0;i<32;i++)p.RAM[0xd98+i]=0;
 const baseline=captureState(p),tracker={...p._campaignTracker};
 const bot=crew.add(4,1),other=crew.add(6,1),fire=spawnItem(p,0,3,1);other.cooldown=1000;
 crew.update();assert.equal(bot.action,'Collecting power-ups');assert.equal(bot.bombsPlaced,0,'do not bomb the block before picking up its neighboring item');assert.equal(bot.target.x,3);assert.equal(bot.target.y,1);
 const advance=n=>{for(let i=0;i<n;i++){crew.update();p.Run();}};advance(30);assert.equal(p.RAM[0xf9b+fire],0);assert.equal(bot.fireRange,2);assert.equal(other.fireRange,1);assert.equal(p.RAM[0x84d]&127,1,'human powers stay independent');assert.equal(tileKind(p,3,1),10);const v=p.VDC[0];assert.deepEqual([v.VRAM[2*v.VScreenWidth+6],v.VRAM[2*v.VScreenWidth+7],v.VRAM[3*v.VScreenWidth+6],v.VRAM[3*v.VScreenWidth+7]],[0x3304,0x3305,0x3314,0x3315],'native pickup redraw removes the icon and retains green ground');
 bot.cooldown=other.cooldown=1000;
 for(const type of [1,2,3,4,5,6,7,9]){bot.x=56;bot.y=24;bot.target=null;bot.route=[];const item=spawnItem(p,type,3,1);crew.update();assert.equal(p.RAM[0xf9b+item],0);p.Run();}
 assert.equal(bot.bombCapacity,2);assert.equal(other.bombCapacity,1);assert.equal(bot.remote,true);assert.equal(bot.speedUp,true);assert.equal(bot.wallPass,true);assert.equal(bot.bombPass,true);assert.ok(bot.fireproof>3500);assert.equal(bot.extraLives,1);assert.equal(bot.pickupsCollected,9);assert.equal(p.RAM[0x84c]&127,1);assert.equal(p.RAM[0x84e],0);assert.equal(p.RAM[0x438],2);assert.equal(p.RAM[0x43a]&0xf0,0);
 p.RAM[0x44a+32+4]=2;assert.equal(canOccupy(p,72,24),false);assert.equal(canOccupy(p,72,24,bot),true,'only a wall-pass actor can cross blocks');p.RAM[0x44a+32+4]=0;assert.equal(canOccupy(p,72,24,{...bot,bombPass:false}),false);assert.equal(canOccupy(p,72,24,bot),true,'bomb pass applies to this actor');p.RAM[0x44a+32+4]=0xca;
 for(let i=0;i<4;i++){spawnItem(p,0,3,1);bot.x=56;bot.y=24;crew.update();p.Run();}assert.equal(bot.fireRange,5,'native fire-up cap');
 // The native explosion reads the range saved for the specific AI bomb, rather
 // than the human's range of one. Remote bombs wait until living actors escape.
 for(let y=1;y<12;y++)for(let x=2;x<15;x++)p.RAM[0x44a+y*32+x]=0xca;for(let i=0;i<25;i++)p.RAM[0xf9b+i]=0;for(let i=0;i<40;i++)p.RAM[0x84f+i]=0;
 bot.x=104;bot.y=88;bot.target=null;bot.route=[];bot.cooldown=0;other.x=40;other.y=56;other.target=null;other.route=[];other.cooldown=1000;p.RAM[0x44a+6*32+6]=0xc2;p.RAM[0x44a+5*32+11]=0xc2;
 crew.update();assert.equal(bot.bombsPlaced,1);const slot=companionBombSlots(bot).find(i=>p.RAM[0x84f+i]&128);assert.notEqual(slot,undefined);assert.equal(crew.state.bombRanges[slot],5);p.Run();crew.update();assert.equal(p.RAM[0x8ef+slot],150,'remote bomb stays held while its owner is in range');p.Run();
 const save=captureState(p),extension=structuredClone(crew.state),tracking={...p._campaignTracker};advance(100);const expected={ram:[...p.RAM],pixels:Uint8ClampedArray.from(p.ImageData.data),bots:structuredClone(crew.state)};assert.equal(tileKind(p,11,5),10,'five-cell native blast destroys the distant block');restoreState(p,save);crew.restore(extension);Object.assign(p._campaignTracker,tracking);advance(100);assert.deepEqual(p.RAM,expected.ram);assert.deepEqual(p.ImageData.data,expected.pixels);assert.deepEqual(crew.state,expected.bots);
 // Fireproof grants flame protection, then expires; an extra life revives after
 // the existing death animation. The human remains untouched by these effects.
 const powered=crew.state.bots[0];powered.x=56;powered.y=24;powered.target=null;powered.cooldown=1000;powered.fireproof=2;p.RAM[0x44a+32+3]=11;crew.update();assert.equal(powered.alive,true);crew.update();assert.equal(powered.alive,false);assert.equal(powered.deathFrame,0);p.RAM[0x44a+32+3]=0xca;advance(DEATH_FRAMES+1);assert.equal(powered.alive,true);assert.equal(powered.extraLives,0);
 const broken=structuredClone(crew.state);broken.bots[0].fireRange=99;assert.throws(()=>validateCompanionState(broken),/power-up/);const legacy=structuredClone(crew.state);delete legacy.bombRanges;for(const b of legacy.bots)for(const k of ['fireRange','speedUp','remote','bombPass','wallPass','fireproof','extraLives','pickupsCollected','remoteTimers'])delete b[k];crew.restore(legacy);assert.equal(crew.state.bots[0].fireRange,1);
 // Isolate a pickup threatened by another bomb: survival outranks collection.
 restoreState(p,baseline);Object.assign(p._campaignTracker,tracker);crew.reset();for(let i=0;i<32;i++)p.RAM[0xd98+i]=0;const cautious=crew.add(4,1),item=spawnItem(p,1,3,1);p.RAM[0x44a+2*32+4]=0xca;spawnBomb(p,4,2);crew.update();assert.equal(p.RAM[0xf9b+item]&128,128);assert.equal(cautious.bombsPlaced,0);assert.equal(cautious.action,'Escaping');
 // Skulls are not beneficial power-ups and do not become pickup objectives.
 restoreState(p,baseline);Object.assign(p._campaignTracker,tracker);crew.reset();for(let i=0;i<32;i++)p.RAM[0xd98+i]=0;const wary=crew.add(4,1);wary.cooldown=1000;spawnItem(p,8,3,1);crew.update();assert.notEqual(wary.action,'Collecting power-ups');assert.equal(pickups(p).some(i=>i.type===8),true);
 restoreState(p,baseline);Object.assign(p._campaignTracker,tracker);crew.reset();for(let i=0;i<32;i++)p.RAM[0xd98+i]=0;for(let y=1;y<12;y++)for(let x=2;x<15;x++)p.RAM[0x44a+y*32+x]=y===3?0xca:1;p.RAM[0x44a+4*32+3]=0xca;p.RAM[0x44a+4*32+4]=0xc2;const protector=crew.add(4,3);protector.fireRange=5;const protectedItem=spawnItem(p,0,8,3);spawnBomb(p,6,3);p.RAM[0x44a+3*32+6]=0;crew.update();assert.equal(protector.bombsPlaced,0,'reject a long blast through an unreachable pickup');assert.ok(p.RAM[0xf9b+protectedItem]&128);
});
test('Battle AI seeks a power-up before combat and the native actor receives its effect',{skip:!rom},()=>{
 const p=createMachine(fs.readFileSync(rom)),ai=createBattleAI(p);ai.configure(2,true,true);for(const a of launchSequence('battle-ai',2))frames(p,a.frames,a.button?[[0,a.button]]:[]);
 const before=p.RAM[0x3ef],x=3,y=1;p.RAM[0x44a+y*32+x]=(p.RAM[0x44a+y*32+x]&224)|7;p.RAM[0xf9b]=128;p.RAM[0xfb4]=x;p.RAM[0xfcd]=y;ai.update();assert.equal(ai.state.plans[0].target.x,x);assert.equal(ai.state.plans[0].target.y,y);
 for(let i=0;i<120&&(p.RAM[0xf9b]&128);i++){ai.update();p.Run();}assert.equal(p.RAM[0xf9b],0);assert.ok(p.RAM[0x3ef]>before,'the native controller actor applies fire up');
});
