import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createMachine,frames} from '../scripts/headless.mjs';import {createCompanions,enemies,DEATH_FRAMES,playerPosition} from '../dist/campaign.js';import {createNewCampaign} from '../dist/new-campaign.js';import {createSpectator,validateSpectatorState} from '../dist/spectator.js';import {launchSequence,createBattleAI,battlePosition} from '../dist/battle-ai.js';import {captureState,restoreState} from '../dist/save-state.js';
const rom=process.env.BOMBERMAN_TEST_ROM;
test('AI-only campaign hides the unused player, follows survivors, fights, finishes and replays saves',{skip:!rom},()=>{
 const p=createMachine(fs.readFileSync(rom)),crew=createCompanions(p,{getHuman:()=>null});let watch;const mode=createNewCampaign(p,{getFocus:()=>watch?.state.enabled?watch.focus():playerPosition(p)});watch=createSpectator(p,{getBots:()=>crew.state.bots});
 for(const a of launchSequence('solo'))frames(p,a.frames,a.button?[[0,a.button]]:[]);frames(p,2520);mode.configure(true,4,12345);mode.update();watch.configure(true);for(const [x,y]of [[2,1],[4,1],[5,1],[6,1]])crew.add(x,y);
 const advance=n=>{for(let i=0;i<n;i++){mode.update();watch.update();crew.update();p.Run();}};
 let nativePixels=0,aiPixels=0;const sprites=p.MakeSpriteLine;p.MakeSpriteLine=function(n){sprites.call(this,n);if(n===0)for(const dot of this.VDC[0].SPLine)if(dot.data){if(dot.no<2)nativePixels++;if(dot.no===64)aiPixels++;}};
 const initial=crew.state.bots.map(b=>({x:b.x,y:b.y}));p.SetButtonRIGHT(0);p.SetButtonSHOT1(0);advance(180);assert.equal(p.Keybord[0][1]&2,2,'native keyboard handlers cannot move the unused human');assert.ok(p.RAM.slice(0x84f,0x859).every(v=>v===0),'only AI bomb banks are used');assert.equal(nativePixels,0,'no human sprite is visible');assert.ok(aiPixels>100,'bots remain visible');assert.ok(crew.state.bots.some((b,i)=>b.x!==initial[i].x||b.y!==initial[i].y));assert.ok(crew.state.bots.some(b=>b.bombsPlaced>0));assert.equal(p.RAM[0x43a]&7,0,'the unused native controller cannot kill the AI session');assert.deepEqual(playerPosition(p),{x:0,y:0});
 const state=captureState(p),bots=structuredClone(crew.state),generator=structuredClone(mode.state),spectator=structuredClone(watch.state),tracker={...p._campaignTracker};advance(60);const expected={ram:[...p.RAM],pixels:Uint8ClampedArray.from(p.ImageData.data),bots:structuredClone(crew.state),watch:structuredClone(watch.state)};restoreState(p,state);crew.restore(bots);mode.restore(generator);watch.restore(spectator);Object.assign(p._campaignTracker,tracker);advance(60);assert.deepEqual(p.RAM,expected.ram);assert.deepEqual(p.ImageData.data,expected.pixels);assert.deepEqual(crew.state,expected.bots);assert.deepEqual(watch.state,expected.watch);
 const lead=crew.state.bots.find(b=>b.id===watch.state.followID);lead.alive=false;lead.deathFrame=0;const survivor=crew.state.bots.find(b=>b.alive)??crew.state.bots.find(b=>b!==lead);survivor.alive=true;survivor.deathFrame=null;survivor.x=392;survivor.y=280;watch.update();mode.update();assert.equal(watch.state.followID,survivor.id);assert.ok((p.RAM[0x25]|p.RAM[0x26]<<8)>100);assert.ok((p.RAM[0x27]|p.RAM[0x28]<<8)>100);assert.equal(watch.state.finished,false);for(const b of crew.state.bots){b.alive=false;b.deathFrame=DEATH_FRAMES;b.extraLives=0;}survivor.extraLives=1;watch.update();assert.equal(watch.state.finished,false,'an unused extra life keeps watching active');survivor.extraLives=0;watch.update();assert.equal(watch.state.finished,true);assert.throws(()=>validateSpectatorState({...watch.state,followID:-1}),/spectator save/);
 // AI reaching a cleared exit can advance without the unused human controller.
 for(let i=0;i<32;i++)p.RAM[0xd98+i]=0;p.RAM[0xd96]=1;p.RAM[0x437]=1;frames(p,1);assert.equal(mode.state.pending,true);mode.update();assert.equal(mode.state.round,2);assert.ok(enemies(p).length>0);
});
test('AI-only Battle drives every native controller, including player one',{skip:!rom},()=>{
 const p=createMachine(fs.readFileSync(rom)),ai=createBattleAI(p);ai.configure(4,true,true);for(const a of launchSequence('battle-ai',4))frames(p,a.frames,a.button?[[0,a.button]]:[]);const start=battlePosition(p,0);for(let i=0;i<180;i++){ai.update();p.Run();}assert.ok(Object.hasOwn(ai.state.plans,'0'));assert.notDeepEqual(battlePosition(p,0),start);assert.ok(ai.state.bombsPlaced>0);p.SetButtonRUN(0);ai.update();assert.equal(p.Keybord[0][0]&8,0,'spectators can use Enter at results');p.UnsetButtonRUN(0);
});
